modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "visor_liquidbacket"
version = "${version}"
displayName = "Visor Liquid Bucket"
authors = "Weever"
displayTest = "NONE"
description = '''
Visor addon for scooping liquid and fish with VR controllers and vanilla buckets.
'''

[[dependencies.visor_liquidbacket]]
modId = "visor"
mandatory = true
versionRange = "[0.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.visor_liquidbacket]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.visor_liquidbacket]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "AFTER"
side = "BOTH"
